[build]
  publish = "public"
  command = "npx playwright install --with-deps chromium && npm run build"
[build.environment]
  NODE_VERSION = "18.15.0"
  NPM_FLAGS = "--legacy-peer-deps"
[[plugins]]
package = "netlify-plugin-gatsby-cache"