[build]
  publish = "public"
  command = "npx playwright install && npm run build"
[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"
[[plugins]]
package = "netlify-plugin-gatsby-cache"