# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "🔍 Search"
  link: /search
- label: Design Patterns
  items:
    - label: Overview
      link: /design-patterns/design-patterns-overview
    - label: Abstract Factory
      link: /design-patterns/abstract-factory-pattern
    - label: Adapter
      link: /design-patterns/adapter-design-pattern
    - label: Builder
      link: /design-patterns/builder-pattern
    - label: Chain of Responsibility
      link: /design-patterns/chain-of-responsibility-pattern
    - label: CQRS
      link: /design-patterns/cqrs-pattern
    - label: Domain Events Pattern
      link: /design-patterns/domain-events-pattern
    - label: Facade
      link: /design-patterns/facade-pattern
    - label: Factory Method
      link: /design-patterns/factory-method-pattern
    - label: Guard Clause
      link: /design-patterns/guard-clause
    - label: Memento
      link: /design-patterns/memento-pattern
    - label: Null Object
      link: /design-patterns/null-object-pattern
    - label: Object Mother
      link: /design-patterns/object-mother-pattern
    - label: Repository
      link: /design-patterns/repository-pattern
    - label: REPR
      link: /design-patterns/repr-design-pattern
    - label: Rules Engine
      link: /design-patterns/rules-engine-pattern
    - label: Singleton
      link: /design-patterns/singleton
    - label: Specification
      link: /design-patterns/specification-pattern
    - label: State
      link: /design-patterns/state-design-pattern
    - label: Strangler Fig
      link: /design-patterns/strangler-fig-pattern
    - label: Strategy
      link: /design-patterns/strategy-pattern
- label: Practices
  items:
    - label: Overview
      link: /practices/practices-overview      
    - label: Authentication
      link: /practices/authentication
    - label: Authorization
      link: /practices/authorization
    - label: Behavior Driven Development
      link: /practices/behavior-driven-development
    - label: Code Readability
      link: /practices/code-readability
    - label: Collective Code Ownership
      link: /practices/collective-code-ownership
    - label: Common Architectural Vision
      link: /practices/common-architectural-vision
    - label: Continuous Integration
      link: /practices/continuous-integration
    - label: Defensive Programming
      link: /practices/defensive-programming
    - label: Dependency Injection
      link: /practices/dependency-injection
    - label: Descriptive Error Messages
      link: /practices/descriptive-error-messages
    - label: Dogfooding
      link: /practices/dogfooding
    - label: Know Where You Are Going
      link: /practices/know-where-you-are-going
    - label: Naming Things
      link: /practices/naming-things
    - label: Pain Driven Development
      link: /practices/pain-driven-development
    - label: Pair Programming
      link: /practices/pair-programming
    - label: Read the Manual
      link: /practices/read-the-manual
    - label: Refactoring
      link: /practices/refactoring
    - label: Rubber Duck Debugging
      link: /practices/rubber-duck-debugging
    - label: Shipping Is A Feature
      link: /practices/shipping-is-a-feature
    - label: Simple Design
      link: /practices/simple-design
    - label: Test Driven Development
      link: /practices/test-driven-development
    - label: Timeboxing
      link: /practices/timeboxing
    - label: Update the Plan
      link: /practices/update-the-plan
    - label: Vertical Slices
      link: /practices/vertical-slices
    - label: Whole Team
      link: /practices/whole-team
    - label: Whole Team Activity
      link: /practices/whole-team-activity
- label: Principles
  items:
    - label: Overview
      link: /principles/principles-overview
    - label: Boy Scout Rule
      link: /principles/boy-scout-rule
    - label: Architectural Agility
      link: /principles/architectural-agility
    - label: Dependency Inversion
      link: /principles/dependency-inversion-principle
    - label: Don't Repeat Yourself
      link: /principles/dont-repeat-yourself
    - label: Encapsulation
      link: /principles/encapsulation
    - label: Explicit Dependencies
      link: /principles/explicit-dependencies-principle
    - label: Fail Fast
      link: /principles/fail-fast
    - label: Hollywood
      link: /principles/hollywood-principle
    - label: Interface Segregation
      link: /principles/interface-segregation
    - label: Inversion of Control
      link: /principles/inversion-of-control
    - label: Keep It Simple
      link: /principles/keep-it-simple
    - label: Principle of Least Astonishment
      link: /principles/principle-of-least-astonishment
    - label: Liskov Substitution
      link: /principles/liskov-substitution-principle
    - label: Once and Only Once
      link: /principles/once-and-only-once
    - label: Open-Closed
      link: /principles/open-closed-principle
    - label: Persistence Ignorance
      link: /principles/persistence-ignorance
    - label: Separation of Concerns
      link: /principles/separation-of-concerns
    - label: Single Responsibility
      link: /principles/single-responsibility-principle
    - label: SOLID
      link: /principles/solid
    - label: Stable Dependencies
      link: /principles/stable-dependencies
    - label: Tell, Don't Ask
      link: /principles/tell-dont-ask
    - label: Tolerance for Imperfection
      link: /principles/tolerance-for-imperfection
    - label: YAGNI
      link: /principles/yagni
- label: Values
  items:
    - label: Overview
      link: /values/values-overview
    - label: Communication
      link: /values/communication
    - label: Courage
      link: /values/courage
    - label: Feedback
      link: /values/feedback
    - label: Respect
      link: /values/respect
    - label: Simplicity
      link: /values/simplicity
- label: Antipatterns
  items:
    - label: Overview
      link: /antipatterns/antipatterns-overview
    - label: Analysis Paralysis
      link: /antipatterns/analysis-paralysis
    - label: Architecture by Implication
      link: /antipatterns/architecture-by-implication
    - label: Assumption Driven Programming
      link: /antipatterns/assumption-driven-programming
    - label: Big Ball of Mud
      link: /antipatterns/big-ball-of-mud
    - label: Big Design Up Front (BDUF)
      link: /antipatterns/big-design-up-front
    - label: The Blob
      link: /antipatterns/blob
    - label: Broken Windows
      link: /antipatterns/broken-windows
    - label: Calendar Coder
      link: /antipatterns/calendar-coder
    - label: Code Smells
      link: /antipatterns/code-smells
    - label: Copy Folder Versioning
      link: /antipatterns/copy-folder-versioning
    - label: Copy Paste Programming
      link: /antipatterns/copy-paste-programming
    - label: Death By Planning
      link: /antipatterns/death-by-planning
    - label: Death March
      link: /antipatterns/death-march
    - label: Duct Tape Coder
      link: /antipatterns/duct-tape-coder
    - label: Exposing Collection Properties
      link: /antipatterns/exposing-collection-properties
    - label: Fast Beats Right
      link: /antipatterns/fast-beats-right
    - label: Feature Creep
      link: /antipatterns/feature-creep
    - label: Flags Over Objects
      link: /antipatterns/flags-over-objects
    - label: Found on Internet
      link: /antipatterns/found-on-internet
    - label: Frankencode
      link: /antipatterns/frankencode
    - label: Frozen Caveman
      link: /antipatterns/frozen-caveman
    - label: Golden Hammer
      link: /antipatterns/golden-hammer
    - label: Iceberg Class
      link: /antipatterns/iceberg-class
    - label: Last 10% Trap
      link: /antipatterns/last-10percent-trap
    - label: Lois Lane Planning
      link: /antipatterns/lois-lane-planning
    - label: Magic Strings
      link: /antipatterns/magic-strings
    - label: Mushroom Management
      link: /antipatterns/mushroom-management
    - label: Not Invented Here
      link: /antipatterns/not-invented-here
    - label: One Thing To Rule Them All
      link: /antipatterns/one-thing-to-rule-them-all
    - label: Reinventing the Wheel
      link: /antipatterns/reinventing-the-wheel
    - label: Service Locator
      link: /antipatterns/service-locator
    - label: Shiny Toy
      link: /antipatterns/shiny-toy
    - label: Singleton
      link: /design-patterns/singleton
    - label: Smoke and Mirrors
      link: /antipatterns/smoke-and-mirrors
    - label: Spaghetti Code
      link: /antipatterns/spaghetti-code
    - label: Static Cling
      link: /antipatterns/static-cling
    - label: Walking Through a Minefield
      link: /antipatterns/walking-through-a-minefield
    - label: Waterfall
      link: /antipatterns/waterfall
    - label: Witches' Brew Architecture
      link: /antipatterns/witches-brew-architecture
- label: Domain Driven Design
  items:
    - label: Overview
      link: /domain-driven-design/ddd-overview
    - label: Aggregate
      link: /domain-driven-design/aggregate-pattern
    - label: Anemic Model
      link: /domain-driven-design/anemic-model
    - label: Anti-Corruption Layer
      link: /domain-driven-design/anti-corruption-layer    
    - label: Bounded Context
      link: /domain-driven-design/bounded-context
    - label: Context Mapping
      link: /domain-driven-design/context-mapping
    - label: Domain
      link: /domain-driven-design/domain
    - label: Domain Model
      link: /domain-driven-design/domain-model
    - label: Domain Storytelling
      link: /domain-driven-design/domain-storytelling
    - label: Entity
      link: /domain-driven-design/entity
    - label: EventStorming
      link: /domain-driven-design/eventstorming
    - label: Shared Kernel
      link: /domain-driven-design/shared-kernel
    - label: Strategic Design
      link: /domain-driven-design/strategic-design
    - label: Subdomain
      link: /domain-driven-design/subdomain
    - label: Tactical Design
      link: /domain-driven-design/tactical-design
    - label: Ubiquitous Language
      link: /domain-driven-design/ubiquitous-language
    - label: Value Object
      link: /domain-driven-design/value-object
- label: Tools
  items:
    - label: Overview
      link: /tools/tools-overview
    - label: Build Server
      link: /tools/build-server
    - label: Version Control
      link: /tools/version-control
- label: Terms
  items:
    - label: Overview
      link: /terms/terms-overview
    - label: Bus Factor
      link: /terms/bus-factor
    - label: Kinds of Models
      link: /terms/kinds-of-models
    - label: Technical Debt
      link: /terms/technical-debt
- label: Testing
  items:
    - label: Overview
      link: /testing/testing-overview
    - label: Arrange-Act-Assert
      link: /testing/arrange-act-assert
- label: Laws
  items:
    - label: Overview
      link: /laws/laws-overview
    - label: Amara's Law
      link: /laws/amaras-law
    - label: Amdahl's Law
      link: /laws/amdahls-law
    - label: Anderson's Law
      link: /laws/andersons-law
    - label: Brooks's Law
      link: /laws/brooks-law
    - label: Conway's Law
      link: /laws/conways-law
    - label: Cunningham's Law
      link: /laws/cunninghams-law
    - label: Law of Demeter
      link: /laws/law-of-demeter
    - label: Law of Diminishing Returns
      link: /laws/law-of-diminishing-returns
    - label: DRY
      link: /principles/dont-repeat-yourself
    - label: Gall's Law
      link: /laws/galls-law
    - label: Linus's Law
      link: /laws/linus-law
    - label: Murphy's Law
      link: /laws/murphys-law
    - label: Postel's Law
      link: /laws/postels-law
    - label: Laws of Architecture
      link: /laws/laws-software-architecture
